method: random
metric:
  name: val_loss
  goal: minimize
parameters:
  dropout_pb:
    values: [0.3, 0.4, 0.5]
  learning_rate:
    values: [0.0001, 0.001, 0.01]
  batch_size:
    values: [32, 64, 128]
  lr_reduce_factor:
    values: [0.5, 0.6, 0.7, 0.8]
  lr_reduce_patience:
    values: [2, 3, 4, 5]
  epochs:
    value: 1
